"""Add coinbase to transaction

Revision ID: 321b2954fdf2
Revises: 94324ba323d4
Create Date: 2025-10-18 18:32:39.295802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '321b2954fdf2'
down_revision: Union[str, None] = '94324ba323d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_transactions', sa.Column('coinbase', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_transactions', 'coinbase')
    # ### end Alembic commands ###
