"""Add addresses index

Revision ID: 94324ba323d4
Revises: d2035abc33cf
Create Date: 2025-10-13 18:31:10.151051

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "94324ba323d4"
down_revision: Union[str, None] = "d2035abc33cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_service_transactions_addresses",
        "service_transactions",
        ["addresses"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_service_transactions_addresses",
        table_name="service_transactions",
        postgresql_using="gin",
    )
    # ### end Alembic commands ###
