"""Add block_index to transaction

Revision ID: c138389e735b
Revises: 321b2954fdf2
Create Date: 2025-10-18 18:39:32.549559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c138389e735b'
down_revision: Union[str, None] = '321b2954fdf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_transactions', sa.Column('block_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_transactions', 'block_index')
    # ### end Alembic commands ###
