"""Remove tx addresses index

Revision ID: d2035abc33cf
Revises: f14d9f9ad604
Create Date: 2025-08-04 11:13:34.498234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2035abc33cf'
down_revision: Union[str, None] = 'f14d9f9ad604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_transactions_addresses'), table_name='service_transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_service_transactions_addresses'), 'service_transactions', ['addresses'], unique=False)
    # ### end Alembic commands ###
