name: "Run tests"

on: ["pull_request", "push", "workflow_dispatch"]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password

        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5.4.0
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          uv sync --dev

      - name: "Make settings.toml"
        run: |
          cp docs/settings.example.toml settings.toml

      - name: "Run tests"
        run: |
          uv run pytest
        env:
          ENV_FOR_DYNACONF: testing
